baseURL = '/'
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
languageCode = 'es-es'
title = "Ceci n'est pas un mariage"
theme = "hugo-scroll"
copyright = '©️ 2023 Isa & Juanma'

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false

[module]
 [[module.mounts]]
  source = 'i18n'
  target = 'data/translations'

[languages]
  [languages.es]   
    title = 'La no boda de Isa y Juanma'
    weight = 1
    contentDir = 'content/es'
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = 'Castellano'
    [languages.es.params]
      subtitle = 'Una fiesta loca'
  [languages.en]
    contentDir = 'content/en'
    title = 'The no wedding of Isa and Juanma'
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2
    [languages.en.params]
      subtitle = 'A crazy party'
  [languages.fr]
    title = "Ceci n'est pas un mariage"
    weight = 3
    contentDir = 'content/fr'
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    [languages.fr.params]
      subtitle = 'Un folie de fête'

[params]
    featured_image = "/images/cecinestpasunmariagev3.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true