baseURL = 'https://cecinestpasunmariage.org/'
languageCode = 'en-us'
title = "Ceci n'est pas un mariage"
theme = "hugo-scroll"
copyright = 'Isa & Juanma'

[params]
    featured_image = "/images/cecinestpasunmariagev3.jpg"