baseURL = '/'
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
languageCode = 'en-us'
title = "La !boda de Isa & Juanma"
theme = "hugo-scroll"
copyright = 'Isa & Juanma'

[params]
    featured_image = "/images/cecinestpasunmariagev3.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true