baseURL = 'https://cecinestpasunmariage.org/'
languageCode = 'en-us'
title = "Ceci n'est pas un mariage"
theme = 'ananke'
copyright = 'Isa & Juanma'

[params]
    featured_image = "/images/cecinestpasunmarriagev3.jpg"